---
- name: Include platform specific vars
  include_vars: "{{ lookup('first_found', vars_files) }}"
  vars:
    vars_files:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "main.yml"
      paths:
        - "vars"

- name: getenforce
  shell: "[ -x /usr/sbin/getenforce ] && /usr/sbin/getenforce"
  failed_when: false
  register: getenforce
  check_mode: no
  changed_when: False
  tags:
    - setup
    - config

- name: Set selinux fact
  set_fact:
    selinux: "{{ getenforce.stdout == 'Enforcing' }}"
  tags:
    - setup
    - config

- name: Install selinux packages
  package:
    name: "{{ selinux_pkg }}"
    state: present
  when: selinux and ansible_os_family == 'RedHat'
  tags:
    - setup

- name: Set sebooleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent }}"
  with_items: "{{ selinux_booleans }}"
  when: selinux | bool
  tags:
    - config
